import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Footer, Header } from "@/components";
import { Work_Sans } from "next/font/google";
const workSans = Work_Sans({ subsets: ["latin"], weight: ["400", "500", "600"] });


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">

            <body className={workSans.className}>
                <Header />
                {children}
                <Footer />
            </body>

        </html>
    );
}
