import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Footer, Header } from "@/components";
import { Work_Sans } from "next/font/google";
import { ReduxProvider } from "@/sagas/provider";
import { ToastContainer } from "react-toastify";
const workSans = Work_Sans({ subsets: ["latin"], weight: ["400", "500", "600"] });
import "react-toastify/dist/ReactToastify.css";
import Layout from "@/components/Layout";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <html lang="en">
            <body className={workSans.className}>
                <ReduxProvider>
                    <Layout >
                        {children}
                    </Layout>
                </ReduxProvider>
                <ToastContainer bodyClassName="font-primary text-sm"></ToastContainer>
            </body>
        </html>
    );
}
